feat: conditional mTLS auth
Escape-Technologies/repeater pull request #9
Opened 2024-03-12 12:02 UTC by QuentinN42

2024-03-12 13:28 UTC, nullswan requested changes

2024-03-12 13:28 UTC, nullswan commented on pkg/roundtrip/roudtrip.go
> +	if httpReq.Header.Get(mTLSHeader) == "true" {
I'd recommend only checking for header presence

2024-03-13 10:22 UTC, Gby56 approved these changes

2024-03-13 10:23 UTC, QuentinN42 commented on pkg/roundtrip/roudtrip.go
> +}
```suggestion
```

2024-03-13 10:26 UTC, merged